# Generated by Django 4.0.6 on 2022-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_red', models.IntegerField()),
                ('color_blue', models.IntegerField()),
                ('color_yellow', models.IntegerField()),
                ('color_green', models.IntegerField()),
                ('color_purple', models.IntegerField()),
                ('color_orange', models.IntegerField()),
            ],
        ),
    ]
